# Generated by Django 2.1.5 on 2020-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('vinyldestination', '0001_initial'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Artist',
        ),
    ]
