# Generated by Django 2.1.5 on 2020-03-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='record',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
