# Generated by Django 2.1.5 on 2020-03-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/records/'),
        ),
    ]
