# Generated by Django 2.1.5 on 2020-03-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0002_auto_20200316_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('year', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
