# Generated by Django 2.1.5 on 2020-03-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0002_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/artists'),
        ),
    ]
