# Generated by Django 2.1.5 on 2020-03-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0003_auto_20200317_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url',
            field=models.URLField(default=0),
        ),
    ]
