# Generated by Django 2.1.5 on 2020-03-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0004_record_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/shops/'),
        ),
        migrations.AddField(
            model_name='stock',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinyldestination.Shop'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vinyldestination.Record'),
        ),
    ]
