# Generated by Django 2.1.5 on 2020-03-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0006_auto_20200324_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='slug',
        ),
    ]
