# Generated by Django 2.1.5 on 2020-03-24 04:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0008_stock_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='shop', unique=True),
        ),
    ]
