# Generated by Django 2.1.5 on 2020-03-24 04:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0010_auto_20200324_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='shop', unique=True),
        ),
    ]
