# Generated by Django 2.1.5 on 2020-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyldestination', '0011_auto_20200324_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
